### PR TITLE
Fix Clang static analyser nit: zero out nmbs_bitfield structs.

### PR DESCRIPTION
**Pull request by JanX2**
Do you have any thoughts on this? Better safe than sorry.

### CODE REVIEW

**Comment by debevv** [comment]
Yup, given the code it won't matter but I like best practices. Can you use `nmbs_bitfield_reset()`? And can you format the code with the provided `.clang-format`?. Thank you

**Comment by JanX2** [comment]
`nmbs_bitfield_reset()` does not work with globals. Took me a while to figure out why the macro was failing to compile in some of the sample code. Any suggestions? Fall back to `= {0}?

**Comment by debevv** [comment]
Yes, `={0}` should be fine, 1 line is better than 2 anyway.
But why do you say `nmbs_bitfield_reset()` doesn't work? It tried something like this:
```c
nmbs_bitfield a;
int main() {
    nmbs_bitfield_reset(a);
}
```
and it compiles as expected.

**Comment by JanX2** [comment]
> Yes, `={0}` should be fine, 1 line is better than 2 anyway. But why do you say `nmbs_bitfield_reset()` doesn't work? It tried something like this:
> 
> ```c
> nmbs_bitfield a;
> int main() {
>     nmbs_bitfield_reset(a);
> }
> ```
> 
> and it compiles as expected.

Yes. But this won’t:
```c
nmbs_bitfield a;
nmbs_bitfield_reset(a);
int main() {
    return 0;
}

**Pull request merged**
