### PR TITLE
Add STM32 porting example

### PR DESCRIPTION
**Pull request by donghoonpark**
STM32 project configuration example to utilize ```nanomodbus``` library.

This project contains
- ioc file: hardware driver configuration. can generate driver package and cmake setting with STM32CubeMX
- CMakeLists.txt: nanomodbus & porting source linking procedure with cmake
- nanomodbus_port.c/h: stm32 implementation about transport handling, server data object mapping ...etc
- .vscode/* : vscode project setting as an example

It have been tested with ```STM32F401CCUx``` chip with [```pymodbus```](https://github.com/pymodbus-dev/pymodbus) client

### CODE REVIEW

**Comment by DongHoonPark** [comment]
I've found that ```nanomodbus``` cannot support multi-rtu server with current structure. Due to only one ```address_rtu``` can be set in ```nmbs_t```. Do you have any plan to support this feature? If you have willing to do it. I'll make pull request including multi-server feature. I will modify my example as single master to avoid confusion.

**Comment by donghoonpark** [comment]
This example now includes both TCP communication using the W5500 and DMA serial communication on the STM32. The dependency on CubeMX, which was initially included in the pull request, has also been removed, enhancing compatibility so that it can be built with just an appropriate compiler and CMake.

**Comment by DanielMartensson** [comment]
> This example now includes both TCP communication using the W5500 and DMA serial communication on the STM32. The dependency on CubeMX, which was initially included in the pull request, has also been removed, enhancing compatibility so that it can be built with just an appropriate compiler and CMake.

Very good! 
The author of this project seems not so be so active. I wonder why.

**Comment by donghoonpark** [comment]
@debevv Is there any requirements or improvements for an acceptance of this PR?

**Comment by debevv** [comment]
@donghoonpark sorry but I usually work on this in my free time.
The PR looks very good, thank you.

**Pull request closed without merging**
