### PR TITLE
two small changes to support native hardware features in embedded (for example hardware DMA and CRC in STM32)

### PR DESCRIPTION
**Pull request by kpvnnov**
In order not to send data from one buffer to another, but to immediately receive data where it is needed (for example, in DMA mode), the buf_rec index is needed in structure nmbs_t.msg, it is used in the nmbs_platform_conf.read function
and nmbs_crc_calc requires the __weak attribute so that this function can be replaced with hardware calculation of the modbus CRC, a polynomial for which is also available in some embedded systems, including STM32
code examples for stm32 using HAL are attached

### CODE REVIEW

**Comment by kpvnnov** [comment]
in HAL STM functions configurations are declared as __Weak  to make  override possible  in case of other  implementations in user file
and in headers files difined as

#if defined (__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050) /* ARM Compiler V6 */
  #ifndef __weak
    #define __weak  __attribute__((weak))
  #endif
  #ifndef __packed
    #define __packed  __attribute__((packed))
  #endif
#elif defined ( __GNUC__ ) && !defined (__CC_ARM) /* GNU Compiler */
  #ifndef __weak
    #define __weak   __attribute__((weak))
  #endif /* __weak */
  #ifndef __packed
    #define __packed __attribute__((__packed__))
  #endif /* __packed */
#endif /* __GNUC__ */

**Comment by kpvnnov** [comment]
or do we need any other way to use our crc16 function
to use the hardware capabilities of calculating the СRC as described in thisa pplication note an4187
https://www.st.com/resource/en/application_note/an4187-using-the-crc-peripheral-on-stm32-microcontrollers-stmicroelectronics.pdf

**Comment by kpvnnov** [comment]
this helps to reduce the cost of the product. you can take a cheaper processor that can handle processing, for example, six streams (ports) at once at high speed. I will make a ready-made example with a makefile a little later.

**Comment by debevv** [comment]
Implemented in https://github.com/debevv/nanoMODBUS/pull/64

**Comment by marcocipriani01** [comment]
Just for other people's reference, here's how I implemented hardware CRC calculation on my STM32H723ZG:

```C
CRC_HandleTypeDef hcrc;
hcrc.Instance = CRC;
hcrc.Init.DefaultPolynomialUse = DEFAULT_POLYNOMIAL_DISABLE;
hcrc.Init.DefaultInitValueUse = DEFAULT_INIT_VALUE_DISABLE;
hcrc.Init.GeneratingPolynomial = 0x8005;
hcrc.Init.CRCLength = CRC_POLYLENGTH_16B;
hcrc.Init.InitValue = 0xFFFF;
hcrc.Init.InputDataInversionMode = CRC_INPUTDATA_INVERSION_BYTE;
hcrc.Init.OutputDataInversionMode = CRC_OUTPUTDATA_INVERSION_ENABLE;
hcrc.InputDataFormat = CRC_INPUTDATA_FORMAT_BYTES;
if (HAL_CRC_Init(&hcrc) != HAL_OK) {
    Error_Handler();
}
```

```C
uint16_t modbusHardwareCRC(const uint8_t* data, uint32_t length, void* arg) {
    const uint16_t crc = HAL_CRC_Calculate(&hcrc, (uint32_t*) data, length);
    return ((uint16_t) (crc << 8)) | ((uint16_t) (crc >> 8));
}
```

In my testing, hardware CRC was ~10 times faster than software CRC. The only drawback of hardware CRC is that it needs to be protected by a mutex if multiple tasks need it, which slows things down significantly. Here's my workaround, which is still, on average, ~5 times faster than software CRC:

```C
uint16_t modbusHardwareCRC(const uint8_t* data, uint32_t length, void* arg) {
    if (osMutexAcquire(crcMutex, 0UL) == osOK) {
        if (HAL_CRC_GetState(&hcrc) == HAL_CRC_STATE_READY) {
            const uint16_t crc = HAL_CRC_Calculate(&hcrc, (uint32_t*) data, length);
            osMutexRelease(crcMutex);
            return ((uint16_t) (crc << 8)) | ((uint16_t) (crc >> 8));
        }
        osMutexRelease(crcMutex);
        return nmbs_crc_calc(data, length, arg);
    }
    return nmbs_crc_calc(data, length, arg);
}
```

I got Modbus over TCP working with the _lwIP_ network stack of the STM32. I'll be testing UART with DMA soon. I'll see what I can share. So far, the library has been rock solid during testing.

**Comment by debevv** [comment]
@marcocipriani01 yes, an STM32 example with lwIP and a custom CRC function would be very useful

**Comment by debevv** [comment]
@kpvnnov can you make a separate pull request with only the STM32 example? And maybe add a script/Makefile so user can build it easily? Thank you

**Comment by kpvnnov** [comment]
ready in [#77](https://github.com/debevv/nanoMODBUS/pull/77)

**Comment by kpvnnov** [comment]
hardcore version with all files included

**Pull request closed without merging**
